# Site settings
name: Given
email: given223@163.com
author: HaoJiwen
url: http://www.yajiji.com
resume_site: https://ahjwen.github.io/arts/
github: https://github.com/ahjwen/
baseurl: "/"
description: 巴拉巴拉巴拉...
meta_description: 从零开始做大佬~
motto: 我会努力的.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: Given

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

